# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/manuggz/Documents/Projects/Bomberman

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/manuggz/Documents/Projects/Bomberman

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manuggz/Documents/Projects/Bomberman/CMakeFiles /home/manuggz/Documents/Projects/Bomberman/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/manuggz/Documents/Projects/Bomberman/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bomberman

# Build rule for target.
Bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bomberman
.PHONY : Bomberman

# fast build rule for target.
Bomberman/fast:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/build
.PHONY : Bomberman/fast

src/Control_Animacion.o: src/Control_Animacion.cpp.o

.PHONY : src/Control_Animacion.o

# target to build an object file
src/Control_Animacion.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Control_Animacion.cpp.o
.PHONY : src/Control_Animacion.cpp.o

src/Control_Animacion.i: src/Control_Animacion.cpp.i

.PHONY : src/Control_Animacion.i

# target to preprocess a source file
src/Control_Animacion.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Control_Animacion.cpp.i
.PHONY : src/Control_Animacion.cpp.i

src/Control_Animacion.s: src/Control_Animacion.cpp.s

.PHONY : src/Control_Animacion.s

# target to generate assembly for a file
src/Control_Animacion.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/Control_Animacion.cpp.s
.PHONY : src/Control_Animacion.cpp.s

src/animacion.o: src/animacion.cpp.o

.PHONY : src/animacion.o

# target to build an object file
src/animacion.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/animacion.cpp.o
.PHONY : src/animacion.cpp.o

src/animacion.i: src/animacion.cpp.i

.PHONY : src/animacion.i

# target to preprocess a source file
src/animacion.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/animacion.cpp.i
.PHONY : src/animacion.cpp.i

src/animacion.s: src/animacion.cpp.s

.PHONY : src/animacion.s

# target to generate assembly for a file
src/animacion.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/animacion.cpp.s
.PHONY : src/animacion.cpp.s

src/mGrpBloques.o: src/mGrpBloques.cpp.o

.PHONY : src/mGrpBloques.o

# target to build an object file
src/mGrpBloques.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mGrpBloques.cpp.o
.PHONY : src/mGrpBloques.cpp.o

src/mGrpBloques.i: src/mGrpBloques.cpp.i

.PHONY : src/mGrpBloques.i

# target to preprocess a source file
src/mGrpBloques.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mGrpBloques.cpp.i
.PHONY : src/mGrpBloques.cpp.i

src/mGrpBloques.s: src/mGrpBloques.cpp.s

.PHONY : src/mGrpBloques.s

# target to generate assembly for a file
src/mGrpBloques.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mGrpBloques.cpp.s
.PHONY : src/mGrpBloques.cpp.s

src/bomba.o: src/bomba.cpp.o

.PHONY : src/bomba.o

# target to build an object file
src/bomba.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/bomba.cpp.o
.PHONY : src/bomba.cpp.o

src/bomba.i: src/bomba.cpp.i

.PHONY : src/bomba.i

# target to preprocess a source file
src/bomba.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/bomba.cpp.i
.PHONY : src/bomba.cpp.i

src/bomba.s: src/bomba.cpp.s

.PHONY : src/bomba.s

# target to generate assembly for a file
src/bomba.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/bomba.cpp.s
.PHONY : src/bomba.cpp.s

src/control_player.o: src/control_player.cpp.o

.PHONY : src/control_player.o

# target to build an object file
src/control_player.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/control_player.cpp.o
.PHONY : src/control_player.cpp.o

src/control_player.i: src/control_player.cpp.i

.PHONY : src/control_player.i

# target to preprocess a source file
src/control_player.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/control_player.cpp.i
.PHONY : src/control_player.cpp.i

src/control_player.s: src/control_player.cpp.s

.PHONY : src/control_player.s

# target to generate assembly for a file
src/control_player.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/control_player.cpp.s
.PHONY : src/control_player.cpp.s

src/dat_nivel.o: src/dat_nivel.cpp.o

.PHONY : src/dat_nivel.o

# target to build an object file
src/dat_nivel.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/dat_nivel.cpp.o
.PHONY : src/dat_nivel.cpp.o

src/dat_nivel.i: src/dat_nivel.cpp.i

.PHONY : src/dat_nivel.i

# target to preprocess a source file
src/dat_nivel.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/dat_nivel.cpp.i
.PHONY : src/dat_nivel.cpp.i

src/dat_nivel.s: src/dat_nivel.cpp.s

.PHONY : src/dat_nivel.s

# target to generate assembly for a file
src/dat_nivel.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/dat_nivel.cpp.s
.PHONY : src/dat_nivel.cpp.s

src/editor.o: src/editor.cpp.o

.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i

.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s

.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/engine/mGrpSprites/CGroup.o: src/engine/mGrpSprites/CGroup.cpp.o

.PHONY : src/engine/mGrpSprites/CGroup.o

# target to build an object file
src/engine/mGrpSprites/CGroup.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CGroup.cpp.o
.PHONY : src/engine/mGrpSprites/CGroup.cpp.o

src/engine/mGrpSprites/CGroup.i: src/engine/mGrpSprites/CGroup.cpp.i

.PHONY : src/engine/mGrpSprites/CGroup.i

# target to preprocess a source file
src/engine/mGrpSprites/CGroup.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CGroup.cpp.i
.PHONY : src/engine/mGrpSprites/CGroup.cpp.i

src/engine/mGrpSprites/CGroup.s: src/engine/mGrpSprites/CGroup.cpp.s

.PHONY : src/engine/mGrpSprites/CGroup.s

# target to generate assembly for a file
src/engine/mGrpSprites/CGroup.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CGroup.cpp.s
.PHONY : src/engine/mGrpSprites/CGroup.cpp.s

src/engine/mGrpSprites/CSprite.o: src/engine/mGrpSprites/CSprite.cpp.o

.PHONY : src/engine/mGrpSprites/CSprite.o

# target to build an object file
src/engine/mGrpSprites/CSprite.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CSprite.cpp.o
.PHONY : src/engine/mGrpSprites/CSprite.cpp.o

src/engine/mGrpSprites/CSprite.i: src/engine/mGrpSprites/CSprite.cpp.i

.PHONY : src/engine/mGrpSprites/CSprite.i

# target to preprocess a source file
src/engine/mGrpSprites/CSprite.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CSprite.cpp.i
.PHONY : src/engine/mGrpSprites/CSprite.cpp.i

src/engine/mGrpSprites/CSprite.s: src/engine/mGrpSprites/CSprite.cpp.s

.PHONY : src/engine/mGrpSprites/CSprite.s

# target to generate assembly for a file
src/engine/mGrpSprites/CSprite.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/mGrpSprites/CSprite.cpp.s
.PHONY : src/engine/mGrpSprites/CSprite.cpp.s

src/engine/util/CFont.o: src/engine/util/CFont.cpp.o

.PHONY : src/engine/util/CFont.o

# target to build an object file
src/engine/util/CFont.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/CFont.cpp.o
.PHONY : src/engine/util/CFont.cpp.o

src/engine/util/CFont.i: src/engine/util/CFont.cpp.i

.PHONY : src/engine/util/CFont.i

# target to preprocess a source file
src/engine/util/CFont.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/CFont.cpp.i
.PHONY : src/engine/util/CFont.cpp.i

src/engine/util/CFont.s: src/engine/util/CFont.cpp.s

.PHONY : src/engine/util/CFont.s

# target to generate assembly for a file
src/engine/util/CFont.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/CFont.cpp.s
.PHONY : src/engine/util/CFont.cpp.s

src/engine/util/LTexture.o: src/engine/util/LTexture.cpp.o

.PHONY : src/engine/util/LTexture.o

# target to build an object file
src/engine/util/LTexture.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTexture.cpp.o
.PHONY : src/engine/util/LTexture.cpp.o

src/engine/util/LTexture.i: src/engine/util/LTexture.cpp.i

.PHONY : src/engine/util/LTexture.i

# target to preprocess a source file
src/engine/util/LTexture.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTexture.cpp.i
.PHONY : src/engine/util/LTexture.cpp.i

src/engine/util/LTexture.s: src/engine/util/LTexture.cpp.s

.PHONY : src/engine/util/LTexture.s

# target to generate assembly for a file
src/engine/util/LTexture.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTexture.cpp.s
.PHONY : src/engine/util/LTexture.cpp.s

src/engine/util/LTimer.o: src/engine/util/LTimer.cpp.o

.PHONY : src/engine/util/LTimer.o

# target to build an object file
src/engine/util/LTimer.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTimer.cpp.o
.PHONY : src/engine/util/LTimer.cpp.o

src/engine/util/LTimer.i: src/engine/util/LTimer.cpp.i

.PHONY : src/engine/util/LTimer.i

# target to preprocess a source file
src/engine/util/LTimer.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTimer.cpp.i
.PHONY : src/engine/util/LTimer.cpp.i

src/engine/util/LTimer.s: src/engine/util/LTimer.cpp.s

.PHONY : src/engine/util/LTimer.s

# target to generate assembly for a file
src/engine/util/LTimer.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/LTimer.cpp.s
.PHONY : src/engine/util/LTimer.cpp.s

src/engine/util/game_manager.o: src/engine/util/game_manager.cpp.o

.PHONY : src/engine/util/game_manager.o

# target to build an object file
src/engine/util/game_manager.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/game_manager.cpp.o
.PHONY : src/engine/util/game_manager.cpp.o

src/engine/util/game_manager.i: src/engine/util/game_manager.cpp.i

.PHONY : src/engine/util/game_manager.i

# target to preprocess a source file
src/engine/util/game_manager.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/game_manager.cpp.i
.PHONY : src/engine/util/game_manager.cpp.i

src/engine/util/game_manager.s: src/engine/util/game_manager.cpp.s

.PHONY : src/engine/util/game_manager.s

# target to generate assembly for a file
src/engine/util/game_manager.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/engine/util/game_manager.cpp.s
.PHONY : src/engine/util/game_manager.cpp.s

src/explosion.o: src/explosion.cpp.o

.PHONY : src/explosion.o

# target to build an object file
src/explosion.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/explosion.cpp.o
.PHONY : src/explosion.cpp.o

src/explosion.i: src/explosion.cpp.i

.PHONY : src/explosion.i

# target to preprocess a source file
src/explosion.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/explosion.cpp.i
.PHONY : src/explosion.cpp.i

src/explosion.s: src/explosion.cpp.s

.PHONY : src/explosion.s

# target to generate assembly for a file
src/explosion.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/explosion.cpp.s
.PHONY : src/explosion.cpp.s

src/fuente_imagen.o: src/fuente_imagen.cpp.o

.PHONY : src/fuente_imagen.o

# target to build an object file
src/fuente_imagen.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/fuente_imagen.cpp.o
.PHONY : src/fuente_imagen.cpp.o

src/fuente_imagen.i: src/fuente_imagen.cpp.i

.PHONY : src/fuente_imagen.i

# target to preprocess a source file
src/fuente_imagen.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/fuente_imagen.cpp.i
.PHONY : src/fuente_imagen.cpp.i

src/fuente_imagen.s: src/fuente_imagen.cpp.s

.PHONY : src/fuente_imagen.s

# target to generate assembly for a file
src/fuente_imagen.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/fuente_imagen.cpp.s
.PHONY : src/fuente_imagen.cpp.s

src/galeria.o: src/galeria.cpp.o

.PHONY : src/galeria.o

# target to build an object file
src/galeria.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/galeria.cpp.o
.PHONY : src/galeria.cpp.o

src/galeria.i: src/galeria.cpp.i

.PHONY : src/galeria.i

# target to preprocess a source file
src/galeria.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/galeria.cpp.i
.PHONY : src/galeria.cpp.i

src/galeria.s: src/galeria.cpp.s

.PHONY : src/galeria.s

# target to generate assembly for a file
src/galeria.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/galeria.cpp.s
.PHONY : src/galeria.cpp.s

src/globo.o: src/globo.cpp.o

.PHONY : src/globo.o

# target to build an object file
src/globo.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/globo.cpp.o
.PHONY : src/globo.cpp.o

src/globo.i: src/globo.cpp.i

.PHONY : src/globo.i

# target to preprocess a source file
src/globo.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/globo.cpp.i
.PHONY : src/globo.cpp.i

src/globo.s: src/globo.cpp.s

.PHONY : src/globo.s

# target to generate assembly for a file
src/globo.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/globo.cpp.s
.PHONY : src/globo.cpp.s

src/item.o: src/item.cpp.o

.PHONY : src/item.o

# target to build an object file
src/item.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/item.cpp.o
.PHONY : src/item.cpp.o

src/item.i: src/item.cpp.i

.PHONY : src/item.i

# target to preprocess a source file
src/item.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/item.cpp.i
.PHONY : src/item.cpp.i

src/item.s: src/item.cpp.s

.PHONY : src/item.s

# target to generate assembly for a file
src/item.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/item.cpp.s
.PHONY : src/item.cpp.s

src/juego.o: src/juego.cpp.o

.PHONY : src/juego.o

# target to build an object file
src/juego.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego.cpp.o
.PHONY : src/juego.cpp.o

src/juego.i: src/juego.cpp.i

.PHONY : src/juego.i

# target to preprocess a source file
src/juego.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego.cpp.i
.PHONY : src/juego.cpp.i

src/juego.s: src/juego.cpp.s

.PHONY : src/juego.s

# target to generate assembly for a file
src/juego.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego.cpp.s
.PHONY : src/juego.cpp.s

src/juego_batalla.o: src/juego_batalla.cpp.o

.PHONY : src/juego_batalla.o

# target to build an object file
src/juego_batalla.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_batalla.cpp.o
.PHONY : src/juego_batalla.cpp.o

src/juego_batalla.i: src/juego_batalla.cpp.i

.PHONY : src/juego_batalla.i

# target to preprocess a source file
src/juego_batalla.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_batalla.cpp.i
.PHONY : src/juego_batalla.cpp.i

src/juego_batalla.s: src/juego_batalla.cpp.s

.PHONY : src/juego_batalla.s

# target to generate assembly for a file
src/juego_batalla.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_batalla.cpp.s
.PHONY : src/juego_batalla.cpp.s

src/juego_historia.o: src/juego_historia.cpp.o

.PHONY : src/juego_historia.o

# target to build an object file
src/juego_historia.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_historia.cpp.o
.PHONY : src/juego_historia.cpp.o

src/juego_historia.i: src/juego_historia.cpp.i

.PHONY : src/juego_historia.i

# target to preprocess a source file
src/juego_historia.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_historia.cpp.i
.PHONY : src/juego_historia.cpp.i

src/juego_historia.s: src/juego_historia.cpp.s

.PHONY : src/juego_historia.s

# target to generate assembly for a file
src/juego_historia.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_historia.cpp.s
.PHONY : src/juego_historia.cpp.s

src/juego_mostrar_gan.o: src/juego_mostrar_gan.cpp.o

.PHONY : src/juego_mostrar_gan.o

# target to build an object file
src/juego_mostrar_gan.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_mostrar_gan.cpp.o
.PHONY : src/juego_mostrar_gan.cpp.o

src/juego_mostrar_gan.i: src/juego_mostrar_gan.cpp.i

.PHONY : src/juego_mostrar_gan.i

# target to preprocess a source file
src/juego_mostrar_gan.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_mostrar_gan.cpp.i
.PHONY : src/juego_mostrar_gan.cpp.i

src/juego_mostrar_gan.s: src/juego_mostrar_gan.cpp.s

.PHONY : src/juego_mostrar_gan.s

# target to generate assembly for a file
src/juego_mostrar_gan.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/juego_mostrar_gan.cpp.s
.PHONY : src/juego_mostrar_gan.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mapa.o: src/mapa.cpp.o

.PHONY : src/mapa.o

# target to build an object file
src/mapa.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mapa.cpp.o
.PHONY : src/mapa.cpp.o

src/mapa.i: src/mapa.cpp.i

.PHONY : src/mapa.i

# target to preprocess a source file
src/mapa.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mapa.cpp.i
.PHONY : src/mapa.cpp.i

src/mapa.s: src/mapa.cpp.s

.PHONY : src/mapa.s

# target to generate assembly for a file
src/mapa.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/mapa.cpp.s
.PHONY : src/mapa.cpp.s

src/menu.o: src/menu.cpp.o

.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/player.o: src/player.cpp.o

.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i

.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s

.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) -f CMakeFiles/Bomberman.dir/build.make CMakeFiles/Bomberman.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Bomberman"
	@echo "... src/Control_Animacion.o"
	@echo "... src/Control_Animacion.i"
	@echo "... src/Control_Animacion.s"
	@echo "... src/animacion.o"
	@echo "... src/animacion.i"
	@echo "... src/animacion.s"
	@echo "... src/mGrpBloques.o"
	@echo "... src/mGrpBloques.i"
	@echo "... src/mGrpBloques.s"
	@echo "... src/bomba.o"
	@echo "... src/bomba.i"
	@echo "... src/bomba.s"
	@echo "... src/control_player.o"
	@echo "... src/control_player.i"
	@echo "... src/control_player.s"
	@echo "... src/dat_nivel.o"
	@echo "... src/dat_nivel.i"
	@echo "... src/dat_nivel.s"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/engine/mGrpSprites/CGroup.o"
	@echo "... src/engine/mGrpSprites/CGroup.i"
	@echo "... src/engine/mGrpSprites/CGroup.s"
	@echo "... src/engine/mGrpSprites/CSprite.o"
	@echo "... src/engine/mGrpSprites/CSprite.i"
	@echo "... src/engine/mGrpSprites/CSprite.s"
	@echo "... src/engine/util/CFont.o"
	@echo "... src/engine/util/CFont.i"
	@echo "... src/engine/util/CFont.s"
	@echo "... src/engine/util/LTexture.o"
	@echo "... src/engine/util/LTexture.i"
	@echo "... src/engine/util/LTexture.s"
	@echo "... src/engine/util/LTimer.o"
	@echo "... src/engine/util/LTimer.i"
	@echo "... src/engine/util/LTimer.s"
	@echo "... src/engine/util/game_manager.o"
	@echo "... src/engine/util/game_manager.i"
	@echo "... src/engine/util/game_manager.s"
	@echo "... src/explosion.o"
	@echo "... src/explosion.i"
	@echo "... src/explosion.s"
	@echo "... src/fuente_imagen.o"
	@echo "... src/fuente_imagen.i"
	@echo "... src/fuente_imagen.s"
	@echo "... src/galeria.o"
	@echo "... src/galeria.i"
	@echo "... src/galeria.s"
	@echo "... src/globo.o"
	@echo "... src/globo.i"
	@echo "... src/globo.s"
	@echo "... src/item.o"
	@echo "... src/item.i"
	@echo "... src/item.s"
	@echo "... src/juego.o"
	@echo "... src/juego.i"
	@echo "... src/juego.s"
	@echo "... src/juego_batalla.o"
	@echo "... src/juego_batalla.i"
	@echo "... src/juego_batalla.s"
	@echo "... src/juego_historia.o"
	@echo "... src/juego_historia.i"
	@echo "... src/juego_historia.s"
	@echo "... src/juego_mostrar_gan.o"
	@echo "... src/juego_mostrar_gan.i"
	@echo "... src/juego_mostrar_gan.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mapa.o"
	@echo "... src/mapa.i"
	@echo "... src/mapa.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/player.o"
	@echo "... src/player.i"
	@echo "... src/player.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

